import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {resultPatch,matchResult,preRaceFavourite} from '../supabase/functions/fpso-settlement/engine.mjs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]);
for(const script of scripts) new vm.Script(script);
const app=scripts.find(s=>s.includes('let state ='));
const context=vm.createContext({console,setTimeout:()=>0,clearTimeout:()=>{},setInterval:()=>0,window:{addEventListener(){}},document:{addEventListener(){},getElementById:()=>({style:{},innerHTML:''})},localStorage:{getItem:()=>null},Date,Intl,AbortSignal,Headers,crypto});
vm.runInContext(app,context);
const evalApp=s=>vm.runInContext(s,context);
const race={id:'r',api_id:'pe1',track:'Randwick',race_number:1,race_time:'2026-10-03T04:00:00Z',status:'open',runners:[{number:1,name:'One'},{number:2,name:'Two'},{number:3,name:'Three'}]};
const result={race_id:'pe1',venue:'Randwick',race_number:1,start_time:race.race_time,status:'final',placings:[{position:1,number:1,win_price:99,place_price:88},{position:2,number:2},{position:3,number:3}]};
const now=new Date(race.race_time).getTime()+1800000;
assert.equal(resultPatch({...race,status:'settled'},result,now),null);
assert.equal(resultPatch(race,{...result,status:'interim'},now).result_state,'awaiting_final');
assert.equal(resultPatch(race,{...result,status:'interim',status_note:'Protest pending'},now).result_state,'protest');
assert.equal(resultPatch(race,{...result,status:'final',status_note:'Protest pending'},now).result_state,'protest');
assert.equal(resultPatch(race,result,now).result_state,'final');
assert.equal(resultPatch(race,result,now).win_div,undefined);
assert.equal(resultPatch(race,result,now).status,undefined);
assert.equal(resultPatch(race,result,now).next_provider_check,'infinity');
assert.equal(resultPatch(race,{...result,placings:[{position:1,number:1},{position:2,number:1}]},now).result_state,'awaiting_final');
assert.equal(resultPatch(race,{...result,runners:[{dead_heat:true}]},now).result_state,'awaiting_final');
assert.equal(matchResult(race,[result,result]),null);
assert.equal(matchResult(race,[{...result,start_time:'2026-09-03T04:00:00Z'}]),null);
assert.equal(matchResult(race,[result]),result);
const live={runners:[{number:1,name:'One',bookmakers:[{key:'sportsbet',win_price:5}]},{number:2,name:'Two',bookmakers:[{key:'sportsbet',win_price:2}]}]};
assert.equal(preRaceFavourite(race,live,now),null);
assert.equal(preRaceFavourite(race,live,new Date(race.race_time).getTime()-180000).number,2);
assert.equal(preRaceFavourite(race,{runners:[{number:1,bookmakers:[{key:'pointsbetau',win_price:1}]}]},new Date(race.race_time).getTime()-180000),null);
context.card=Array.from({length:10},(_,i)=>({...race,race_number:i+1,api_id:'pe'+i}));
assert.equal(evalApp('validateCard(card).length'),0); // same meeting manual unrestricted
assert.ok(evalApp('validateCard(card.slice(0,9)).length'));
assert.ok(evalApp('validateCard([...card.slice(0,9),card[0]]).length'));
evalApp("state.races=[{...card[0],status:'settled',result_1st:2,result_2nd:1,result_3rd:3,win_div:5,place_div:2,place_div_2nd:1.5,place_div_3rd:1.2,favourite_number:2,pre_race_favourite:{number:2},runners:[{number:1,name:'Original',scratched:true},{number:2,name:'Favourite'},{number:3,name:'Third'}]}]");
assert.equal(evalApp("calculateScores([{selections:{r:1}}])[0].total"),7);
assert.match(evalApp('selectionLabel(state.races[0],1)'),/Original.*SCRATCHED → #2 Favourite/);
assert.equal(evalApp("raceLifecycle({status:'open',result_state:'protest'})"),'PROTEST / RESULT NOT FINAL');
assert.equal(evalApp("raceLifecycle({status:'settled'})"),'Final');
evalApp('showToast=()=>{};filterLoadedRaces=()=>{};renderDraftSummary=()=>{};clearGeneratedCard=()=>{};');
const nodes=new Map();
context.document.getElementById=id=>{if(!nodes.has(id))nodes.set(id,{style:{},value:id==='race-date-input'?'2026-10-03':'',innerHTML:'',insertAdjacentHTML(){}});return nodes.get(id);};
context.card=Array.from({length:15},(_,i)=>({id:'auto'+i,track:'Meeting '+Math.floor(i/3),race_number:i%3+1,time:new Date(new Date(race.race_time).getTime()+i*1200000).toISOString(),class:'',active_runners:8,runners:Array.from({length:8},(_,n)=>({number:n+1,name:'Horse '+n}))}));
evalApp('loadedRacingCard=card;autoGenerateCard();');
assert.equal(evalApp('loadedRacingCard.filter(r=>r.autoSelected).length'),10);
assert.equal(evalApp('Math.max(...Object.values(loadedRacingCard.filter(r=>r.autoSelected).reduce((a,r)=>(a[r.track]=(a[r.track]||0)+1,a),{})))'),2);
const meetings=context.card.slice(0,10).map(r=>({venue:r.track,races:[{race_number:r.race_number,start_time:r.time,runners:r.runners}]}));
context.fetch=async()=>({ok:true,json:async()=>({meetings:[...meetings,{venue:'Mungery Picnic',races:[{race_number:1,runners:[]}]}]})});
await evalApp('loadRaceCard()');
assert.equal(nodes.get('auto-card-btn').style.display,'inline-flex');
context.fetch=async()=>({ok:true,json:async()=>({meetings:[...meetings,{venue:'Normal Meeting',races:[{race_number:1,runners:[]}]}]})});
await evalApp('loadRaceCard()');
assert.equal(nodes.get('auto-card-btn').style.display,'none');
console.log('PASS: syntax, final/interim/protest gates, bad payloads, protected final, match identity/date, dividend provenance, capture timing, card validation, scratching scoring, Auto Generate max 2, picnic exception and normal untimed fail-closed');
